### ISSUE TITLE
update to svgo 3?

### ISSUE THREAD

**Issue by felixsanz** [porsager/rollup-plugin-svgo#14]

**Comment by jasongitmail** [comment]
Came here to suggest this as well. svgo [v3.0.2 is available](https://github.com/svg/svgo/blob/main/package.json).

**Comment by jasongitmail** [comment]
Would it be fair to consider this unmaintained? I'm curious the reason for closing given it's core to the plugin.

**Comment by porsager** [comment]
The author of the issue closed it, not me. 

And yes, I don't use this myself anymore, but anyone can fork if they feel like. I'll be happy to point to something else in the readme, or add another maintainer 👍

**Comment by porsager** [comment]
Not much usually happens though, people just want someone else to do their work for them  😬 
 
see eg https://github.com/porsager/rollup-plugin-svgo/issues/12

**Comment by felixsanz** [comment]
> people just want someone else to do their work for them 😬

no, you're the owner, I expected you to maintain it (it's not a feature just a version bump)

But this is open source so... you are not doing anything wrong by not wanting to maintain it and I am not doing anything wrong by closing an issue that is not even answered or attended in a year

**Comment by porsager** [comment]
I actually wasn't referring to you directly, but now that you mention it, this could have been a pull request 😉

The fact that I referred to you was only in regards to @jasongitmail asking "why" the issue was closed — I didn't blame you for closing it? Why would I?

**Comment by felixsanz** [comment]
> I actually wasn't referring to you directly, but now that you mention it, this could have been a pull request 😉
> 
> The fact that I referred to you was only in regards to @jasongitmail asking "why" the issue was closed — I didn't blame you for closing it? Why would I?

ah ok, I thought that "people just want someone else to do their work for them" was referring to me 😜

no problem then, cheers

PS: i can PR but i can't publish to npm, so it doesn't make much sense to change a number in package.json if it's abandoned, I created the issue and got no replies for 5 months xD

**Comment by felixsanz** [comment]
PS: i can PR but i can't publish to npm, so it doesn't make much sense to change a number in package.json if it's abandoned
