### ISSUE TITLE
rollup-plugin-svgo depends on version of nth-check with security flaw

### ISSUE THREAD

**Issue by richardmarston** [porsager/rollup-plugin-svgo#8]
Github's dependabot is reporting a security flaw with one of the dendencies of this project. I think the fix is just to upgrade the svgo dependency to 2.8.0.

Here is a screenshot of the dependabot report:

![nth-check](https://user-images.githubusercontent.com/994657/146384411-0206b031-d5c4-4def-bcc3-4cf8c80d15b5.png)

**Comment by porsager** [comment]
Thanks richard.. Should have been done a lot sooner.. I'll just test a v2 beta out on my projects and I'll release with the update.
